version: '3'

services:
  sursu-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - log_volume:/app/logs
    env_file:
      - .env

volumes:
  log_volume:
